version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip"
      - "unzip terraform_1.3.0_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
      - "npm install"
    pre_build:
      commands:
        - "terraform init"

    build:
      commands:
        - "npm run build"
        - "terraform apply --auto-approve"

    post_build:
      commands:
        - echo terraform apply completed on 'date'